### ISSUE TITLE
No Ascendancy Image

### ISSUE THREAD

**Issue by mattmarich** [FWidm/discord-pob#3]
First of all, great work! I have this hosted on our server using python3.6 and the requirements installed but for some reason the ascendancy images are not displaying when this is invoke. please see the following screenshot

https://puu.sh/zRHSp/05cf524791.png

I enabled debugging but I'm not seeing a means for me to troubleshoot this.

**Comment by FWidm** [comment]
Hi, thanks - could you check if you are you on the latest master branch currently? I think I've renamed the folder that contains the images recently so that might have changed something for you too. Be sure to also update your config.py by either adding missing entries. The current one for both master and experimental should look like this:
```python
import logging

# -- Rename this file to config.py! --

import os
# Enter discord token from https://discordapp.com/developers/applications/me/
token = 'yoursupersecrettoken'
# color of the embed
color = 0x859900
# keywords to trigger the bot in passive channels
keywords = ['!pob']
# reacts to pastebin posts with pob info in these channels
active_channels = ['pob']
# debug level
debug_level = logging.DEBUG
# bot status (presence) message
presence_message = '!pob <pastebin>'
# This is your Project Root
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
```
I've added the thumbnail to the debug messages as well in the newest version on the `experimental`-branch if pulling the newest master won't work  - the line looks like this now:

`2018-03-29 - 08:46:55 discord_pob  DEBUG    embed=<discord.embeds.Embed object at 0x10c75f168>; thumbnail=EmbedProxy(url='https://raw.githubusercontent.com/FWidm/discord-pob/master/_img/Elementalist.png'); length=120`

Let me know if this solves the issue :).

**Comment by FWidm** [comment]
My bad, gladi image does not exist, should be fixed with the last commit, feel free to report further issues.
