### ISSUE TITLE
Not able to start the bot

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [FWidm/discord-pob#5]
> $ python discord_pob.py
> Traceback (most recent call last):
>   File "discord_pob.py", line 2, in <module>
>     from src.bot.discord_bot import bot
>   File "C:\Discord Bot\POB\src\bot\discord_bot.py", line 6, in <module>
>     import discord
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
>     from .client import Client, AppInfo, ChannelPermissions
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
>     from .state import ConnectionState
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
>     from . import utils, compat
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\compat.py", line 32
>     create_task = asyncio.async
>                               ^
> SyntaxError: invalid syntax

This is all I get when I try to start the bot.
Is there anything I can do ?

**Comment by FWidm** [comment]
Hi, according to the python discord bot library I am currently using this is due to `import` becoming a keyword in python 3.7 [more info here](https://github.com/Rapptz/discord.py/issues/1249).

So I'd recommend installing anything between python 3.4 and 3.6 and it should work flawlessly. Let me know if you need more help.
